import React from 'react';

export const STITCH_THEME = {
  colors: {
    bgPrimary: '#07090E',
    bgSecondary: '#0C1018',
    bgCard: 'rgba(13, 17, 26, 0.85)',
    bgCardElevated: 'rgba(18, 24, 38, 0.95)',
    borderSubtle: 'rgba(255, 255, 255, 0.08)',
    borderActive: 'rgba(0, 240, 255, 0.4)',
    borderCyanGlow: '0 0 16px rgba(0, 240, 255, 0.25)',
    borderVioletGlow: '0 0 16px rgba(121, 40, 202, 0.25)',
    textPrimary: '#F8FAFC',
    textSecondary: '#94A3B8',
    textMuted: '#64748B',
    accentCyan: '#00F0FF',
    accentViolet: '#7928CA',
    accentEmerald: '#10B981',
    accentAmber: '#F59E0B',
    accentCrimson: '#EF4444',
    accentRose: '#FF0055',
  },
  typography: {
    fontMono: "'SF Mono', 'Fira Code', Menlo, Consolas, monospace",
    fontSans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },
  styles: {
    glassCard: {
      backgroundColor: 'rgba(13, 17, 26, 0.85)',
      backdropFilter: 'blur(16px)',
      WebkitBackdropFilter: 'blur(16px)',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      borderRadius: '12px',
    } as React.CSSProperties,
    glassCardElevated: {
      backgroundColor: 'rgba(18, 24, 38, 0.95)',
      backdropFilter: 'blur(20px)',
      WebkitBackdropFilter: 'blur(20px)',
      border: '1px solid rgba(0, 240, 255, 0.25)',
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.6)',
      borderRadius: '14px',
    } as React.CSSProperties,
    primaryButton: {
      background: 'linear-gradient(135deg, #00F0FF 0%, #0070F3 100%)',
      color: '#000000',
      fontWeight: 600,
      fontSize: '13px',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      padding: '8px 18px',
      borderRadius: '8px',
      border: 'none',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      transition: 'all 0.15s ease',
    } as React.CSSProperties,
    secondaryButton: {
      background: 'rgba(255, 255, 255, 0.05)',
      color: '#F8FAFC',
      fontWeight: 500,
      fontSize: '13px',
      padding: '8px 16px',
      borderRadius: '8px',
      border: '1px solid rgba(255, 255, 255, 0.12)',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      transition: 'all 0.15s ease',
    } as React.CSSProperties,
    dangerButton: {
      background: 'rgba(239, 68, 68, 0.15)',
      color: '#EF4444',
      fontWeight: 600,
      fontSize: '13px',
      padding: '8px 16px',
      borderRadius: '8px',
      border: '1px solid rgba(239, 68, 68, 0.3)',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
    } as React.CSSProperties,
    // WCAG 2.1 AA Compliant Accessible Button Base (>= 44x44px touch target)
    accessibleTouchTarget: {
      minWidth: '44px',
      minHeight: '44px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
    } as React.CSSProperties,
    // Visible High-Contrast Focus Ring for Keyboard Navigation
    focusVisibleRing: {
      outline: '2px solid #00F0FF',
      outlineOffset: '2px',
      boxShadow: '0 0 12px rgba(0, 240, 255, 0.5)',
    } as React.CSSProperties,
    // Screen Reader Only Utility
    visuallyHidden: {
      position: 'absolute',
      width: '1px',
      height: '1px',
      padding: '0',
      margin: '-1px',
      overflow: 'hidden',
      clip: 'rect(0, 0, 0, 0)',
      whiteSpace: 'nowrap',
      borderWidth: '0',
    } as React.CSSProperties,
    input: {
      backgroundColor: 'rgba(255, 255, 255, 0.04)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '8px',
      padding: '8px 12px',
      color: '#F8FAFC',
      fontSize: '13px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      outline: 'none',
      boxSizing: 'border-box',
    } as React.CSSProperties,
  },
};

